apiVersion: apps/v1
kind: Deployment
metadata:
  name: classnotes-deployment
  labels:
    app: classnotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classnotes
  template:
    metadata:
      labels:
        app: classnotes
    spec:
      containers:
      - name: classnotes
        image: lgrez/classnotes_api:v1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 4004
          name: fastapi
        readinessProbe:
          httpGet:
            port: 4004
            path: /docs
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
            port: 4004
            path: /docs
          initialDelaySeconds: 15
          periodSeconds: 15
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "1"


        env:
        - name: PYTHONPATH
          value: "/app"
        - name: SERVER_NAME
          valueFrom:
            secretKeyRef:
              name: classnotes-secret
              key: SERVER_NAME
        - name: SERVER_HOST
          valueFrom:
            secretKeyRef:
              name: classnotes-secret
              key: SERVER_HOST
        - name: PROJECT_NAME
          valueFrom:
            secretKeyRef:
              name: classnotes-secret
              key: PROJECT_NAME
        - name: FIRST_SUPERUSER
          valueFrom:
            secretKeyRef:
              name: classnotes-secret
              key: FIRST_SUPERUSER
        - name: FIRST_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: classnotes-secret
              key: FIRST_SUPERUSER_PASSWORD
        - name: USERS_OPEN_REGISTRATION
          valueFrom:
            secretKeyRef:
              name: classnotes-secret
              key: USERS_OPEN_REGISTRATION
        - name: BACKEND_CORS_ORIGINS
          valueFrom:
            secretKeyRef:
              name: classnotes-secret
              key: BACKEND_CORS_ORIGINS

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_SERVER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_SERVER
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: PGADMIN_DEFAULT_EMAIL
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: PGADMIN_DEFAULT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: classnotes-service
spec:
  type: NodePort
  selector:
    app: classnotes
  ports:
    - port: 4004
      targetPort: 4004
      nodePort: 30404
