version: '3.8'

services:
  fastapi-app:
    container_name: courses-fastapi-app
    build: .
    image: fast_api_base
    env_file:
      - .env
    ports:
      - "4005:4005"
    volumes:
      - ./app:/app
    depends_on:
      - db
    command: "uvicorn main:app --host 0.0.0.0 --port 4005 --reload"

  db:
    container_name: courses_postgresql_db
    image: postgres:16

    ports:
      - "5006:5006"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata



volumes:
  postgres_data:
