apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: lgrez/signup_api:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 4002
          name: fastapi-users
        readinessProbe:
          httpGet:
            port: 4002
            path: /docs
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
            port: 4002
            path: /docs
          initialDelaySeconds: 15
          periodSeconds: 15
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.25"
          limits:
            memory: "512Mi"
            cpu: "0.5"


        env:
        - name: PYTHONPATH
          value: "/app"
        - name: SERVER_NAME
          valueFrom:
            secretKeyRef:
              name: users-secret
              key: SERVER_NAME
        - name: SERVER_HOST
          valueFrom:
            secretKeyRef:
              name: users-secret
              key: SERVER_HOST
        - name: PROJECT_NAME
          valueFrom:
            secretKeyRef:
              name: users-secret
              key: PROJECT_NAME
        - name: FIRST_SUPERUSER
          valueFrom:
            secretKeyRef:
              name: users-secret
              key: FIRST_SUPERUSER
        - name: FIRST_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: users-secret
              key: FIRST_SUPERUSER_PASSWORD
        - name: USERS_OPEN_REGISTRATION
          valueFrom:
            secretKeyRef:
              name: users-secret
              key: USERS_OPEN_REGISTRATION
        - name: BACKEND_CORS_ORIGINS
          valueFrom:
            secretKeyRef:
              name: users-secret
              key: BACKEND_CORS_ORIGINS

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_SERVER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_SERVER
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: PGADMIN_DEFAULT_EMAIL
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: PGADMIN_DEFAULT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  type: NodePort
  selector:
    app: users
  ports:
    - port: 4002
      targetPort: 4002
      nodePort: 30402
