version: '3.1'

services:
  fastapi-app:
    container_name: classnotes-redis-fastapi-app
    build: .
    image: fast_api_base
    
    env_file:
      - .env

    ports:
      - "8000:83"
    volumes:
      - .:/app
    command: "uvicorn app.main:app --host 0.0.0.0 --port 83 --reload"
